<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="X390" ignored="0" name="Test(failed)" tests="2" failures="2" timestamp="2022-07-18T21:03:41 EDT" time="0.001" errors="0">
  <testcase name="TestNG3" time="0.0" classname="com.runFaileTestCase1.demo2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.runFaileTestCase1.demo2.TestNG3(demo2.java:10)
at java.util.ArrayList.forEach(Unknown Source)
at com.runFaileTestCase1.FailTestRunner.runFailTestCses(FailTestRunner.java:17)
... Removed 52 stack frames]]>
    </failure>
  </testcase> <!-- TestNG3 -->
  <testcase name="TestNG4" time="0.0" classname="com.runFaileTestCase1.demo2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.runFaileTestCase1.demo2.TestNG4(demo2.java:15)
at java.util.ArrayList.forEach(Unknown Source)
at com.runFaileTestCase1.FailTestRunner.runFailTestCses(FailTestRunner.java:17)
... Removed 52 stack frames]]>
    </failure>
  </testcase> <!-- TestNG4 -->
</testsuite> <!-- Test(failed) -->
